Allow configuring min size of checksum deploy in Gradle
jfrog/build-info pull request #408
Opened 2020-11-06 17:27 UTC by yahavi

- [x] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/build-info) passed. If this feature is not already covered by the tests, I added new tests.
-----
#341 

Instead of using 10MB, allow configuring the minimal file size of checksum deploy:
```gradle
allProjects {
    artifactoryPublish {
        clientConfig.publisher.checksumDeployMinFileSize = 123
    }
}
```

2020-11-16 09:47 UTC, staffanf commented
> Instead of using 10MB, allow configuring the minimal file size of checksum deploy:

I think that should be 10KB right?

Otherwise these changes looks good (too me). I guess it should be documented somewhere?

2020-11-16 10:10 UTC, yahavi commented
> > Instead of using 10MB, allow configuring the minimal file size of checksum deploy:
> 
> I think that should be 10KB right?
> 
> Otherwise these changes looks good (too me). I guess it should be documented somewhere?

Right. Thanks!
The code first have to be peer reviewed by @eyalbe4. If everything is OK, the feature will be included and documented in the next release.

2020-11-29 13:00 UTC, eyalbe4 requested changes

2020-11-30 07:35 UTC, yahavi commented on build-info-api/src/main/java/org/jfrog/build/api/BuildInfoFields.java
> +    String CHECKSUM_DEPLOY_MIN_FILE_SIZE = "checksumDeployMinFileSize";
We agreed to leave it camel case

2020-11-30 07:51 UTC, merged