HTTP requests should return CloseableHttpResponse
jfrog/build-info pull request #424
Opened 2020-12-16 13:01 UTC by yahavi

- [x] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/build-info) passed. If this feature is not already covered by the tests, I added new tests.
-----

Replace HttpReponse by CloseableHttpResponse to allow closing responses after HTTP requests.

Related to: https://www.jfrog.com/jira/browse/HAP-1422

2020-12-20 14:59 UTC, eyalbe4 requested changes

2020-12-20 14:59 UTC, eyalbe4 commented on build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/DockerUtils.java
> +        response.close();
We better put ```response.close()``` inside a ```finally``` in case ```EntityUtils.consume``` throws an exception.

2020-12-20 14:59 UTC, eyalbe4 commented on build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/Utils.java
> +            response.close();
We better put ```response.close()``` inside a finally in case ```dependenciesClient.getArtifactMetadata``` throws an exception.

2020-12-20 14:59 UTC, eyalbe4 commented on build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/ArtifactoryBuildInfoClient.java
> +        response.close();
We better put ```response.close()``` inside a finally in case ```sendHttpRequest``` throws an exception.

2020-12-21 07:10 UTC, yahavi commented on build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/types/DockerImage.java
> +            entity = res.getEntity();
It is in use in the finally clause

2020-12-21 07:57 UTC, yahavi commented on build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/types/DockerImage.java
> +            EntityUtils.consume(entity);
I disagree because the `consume` will take place in the `finally` clause.

2020-12-21 10:23 UTC, merged