Publish Gradle plugin to Gradle Gallery
jfrog/build-info pull request #536
Opened 2021-07-15 07:55 UTC by yahavi

- [x] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/build-info) passed. If this feature is not already covered by the tests, I added new tests.
-----

Resolves https://github.com/jfrog/build-info/issues/518

Check every 4 hours if the `build-info-extractor-gradle` version in the Maven Central is newer than the latest published in the Gradle gallery. If it does, update the version in the Gradle Gallery.

2021-07-15 16:13 UTC, eyalbe4 requested changes

2021-07-15 16:13 UTC, eyalbe4 commented on .github/workflows/gradle.yml
> +name: "Publish to Gradle Gallery"
I suggest adding to thsi workflow a description, explaining why we created this workflow as a cron, and explain the entire release flow.

2021-07-15 16:37 UTC, merged

2021-07-15 21:40 UTC, NiazBikbaev commented on .github/workflows/gradle.yml
> +          export LATEST_MVN_CENTRAL_VERSION=`curl -s https://search.maven.org/solrsearch/select\?q\=g:"org.jfrog.buildinfo"+AND+a:"build-info-extractor-gradle" | jq -r '.response.docs[0].latestVersio
@yahavi there is a typo in curl commnd :)
`jq -r '.response.docs[0].latestVersio`

Thats why scheduled job failed https://github.com/jfrog/build-info/runs/3080541646?check_suite_focus=true

2021-07-16 04:20 UTC, eyalbe4 commented on .github/workflows/gradle.yml
> +# To solve this out, this workflow runs every 4 hours to check if the Gradle plugin should be published to the Gradle
To solve this out, this... --> To solve this issue, this...