Split build-info class
jfrog/build-info pull request #559
Opened 2021-10-07 09:11 UTC by Or-Geva

- [x] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/build-info) passed. If this feature is not already covered by the tests, I added new tests.
-----
Until now, Build-info-java has one class that includes all the build-info schema properties & extra logic. Examples of build-info logic are recording artifacts/dependencies local path or append modules/builds.

The one-class structure needs to be splitted into two classes. The first class would have only build-info properties that Artifactory will be using, and the second would have all the extra logic + properties which will be used by other consumers (Jenkins).

2021-10-20 15:54 UTC, eyalbe4 requested changes
I'm not done reviewing everything, but I'm sharing what I have so far.
I'll continue reviewing the rest soon.

2021-10-20 15:54 UTC, eyalbe4 commented on build-info-api/src/main/java/org/jfrog/build/api/builder/BuildBuilder.java
> +    public BuildBuilder licenseControl(LicenseControl licenseControl) {
This method, in addition to everything that is around license control should be removed. I suggest we delete the LicenseControl class, and then remove everything that uses it.

2021-11-07 10:34 UTC, Or-Geva commented on build-info-api/src/main/java/org/jfrog/build/api/builder/BuildInfoBuilder.java
>          if (StringUtils.isNotBlank(version)) {
The If makes sure that the default version in `new BuildInfo();` won't get an override.

2021-11-07 13:17 UTC, Or-Geva commented on build-info-api/src/main/java/org/jfrog/build/api/builder/BuildInfoModuleBuilder.java
> +public class BuildInfoModuleBuilder {
BuildModuleBuilder - build the old 'build' class (used by Artifactory)
BuildInfoModuleBuilder - build the new 'build' class (used by Jenkins, etc..)

2021-11-22 13:23 UTC, eyalbe4 requested changes

2021-11-22 13:23 UTC, eyalbe4 commented on build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoZipBallStreamer.java
> - */
We need to keep this specific declaration.

2021-11-22 13:23 UTC, eyalbe4 commented on build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildDeploymentHelper.java
> +                       File basedir) {
Let's use this opportunity and align the above code lines according to our conventions.

2021-12-12 06:25 UTC, merged