Bugfix - Gradle defaults props should not ignore deprecated build-inf…
jfrog/build-info pull request #590
Opened 2021-12-20 14:44 UTC by Or-Geva

…o properties

- [ ] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/build-info) passed. If this feature is not already covered by the tests, I added new tests.
-----
Build-info properties file may include deprecated properties that have 'artifactory' as their prefix. since Gradle may generate defaults to the none deprecated keys we need to look for the deprecated keys first.

2021-12-27 08:38 UTC, eyalbe4 requested changes

2021-12-27 08:38 UTC, eyalbe4 commented on build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/PrefixPropertyHandler.java
>          // TODO: throw exception if not true or false. If prop set to something else
This TODO comment should be probably removed.

2021-12-27 08:38 UTC, eyalbe4 commented on build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/PrefixPropertyHandler.java
> +        value = props.get(prefix + key);
The above flow, of fetching the deprecated value, and if null, falling back to the non-deprecated value, is duplicated three times in the class. Better to take it into a separate method, and reuse it.

2021-12-27 08:38 UTC, eyalbe4 commented on build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/GradlePluginTest.java
> +    public void deprecatedCiServerTest(String gradleVersion) throws IOException {
Let;s add a description, explaining what's tested by this function. The random reader will not know what's deprecated, why and what this test is all about.

2021-12-27 15:18 UTC, merged

2022-08-05 14:49 UTC, yahavi commented on build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/GradlePluginTest.java
> +        // Check results
Looks like this line is missing below "Check results":
```
checkBuildResults(artifactoryManager, buildResult, VersionNumber.parse(gradleVersion).getMajor() >= 6, localRepo1);
```