Merge property file reading logic
jfrog/build-info pull request #769
Opened 2023-12-04 08:25 UTC by Or-Geva

- [ ] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/build-info) passed. If this feature is not already covered by the tests, I added new tests.
-----

2023-12-06 13:53 UTC, yahavi requested changes
I'd like to review the tests after fixing them

2023-12-11 16:04 UTC, Or-Geva commented on build-info-extractor/src/test/java/org/jfrog/build/extractor/BuildExtractorUtilsTest.java
> +        createProperty();
You're right, it should be `setupEncryptedFileTest(createProperty());` and we are removing the keys on line 117

2023-12-11 16:08 UTC, Or-Geva commented on build-info-extractor/src/test/java/org/jfrog/build/extractor/BuildExtractorUtilsTest.java
> +    private Properties createPropertyEnv() {
It generates slightly different properties apart from using createProperty to specifically handle properties associated with environment reads, distinguishing them from file-related properties.

2023-12-11 16:19 UTC, yahavi approved these changes
LGTM

2023-12-11 16:30 UTC, merged