Resolved Issue with Running 'go' Command on Windows in Paths with Spaces
jfrog/build-info pull request #772
Opened 2023-12-14 12:38 UTC by noyshabtay

- [ ] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/build-info) passed. If this feature is not already covered by the tests, I added new tests.
-----

2023-12-17 08:02 UTC, Or-Geva requested changes

2023-12-17 08:02 UTC, Or-Geva commented on build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/GoDriver.java
> +        }
Let's add a comment here.

2023-12-17 08:02 UTC, Or-Geva commented on build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/GoDriver.java
> +    private static CommandExecutor generateCommandExecutor(String executablePath, Map<String, String> env) {
We can include tests for this function that cover all possible cases. Each test can provide an explanation of what it aims to check and why.

2023-12-19 15:23 UTC, yahavi requested changes

2023-12-19 15:23 UTC, yahavi commented on build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/GoDriver.java
> +    private static final String defaultExecutablePath = "go";
```suggestion
    private static final String DEFAULT_EXECUTABLE_NAME = "go";
```

Let's also put it above, near the other private static final variables.

2023-12-19 15:23 UTC, yahavi commented on build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/GoDriver.java
> +        // Handling Windows case:
But Windows cases can be in the above "if" too. Can we rearrange the code? Specifically, I'd simplify the "if" above.

2023-12-19 15:23 UTC, yahavi commented on build-info-extractor-go/src/test/java/org/jfrog/build/extractor/go/GoDriverTest.java
> +            throw new SkipException("Skipping Windows test");
On the contrary - you skip non-windows tests

2023-12-19 15:23 UTC, yahavi commented on build-info-extractor-go/src/test/java/org/jfrog/build/extractor/go/GoDriverTest.java
> +            new GoDriver(executablePath, systemEnv, projectDir, new NullLog());
What does this line do?

2023-12-20 08:55 UTC, merged